apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-config
  namespace: cloudnote
data:
  BASE_URL: "https://myclass.lpu.in/"
  HEADLESS: "True"
  LOG_LEVEL: "INFO"
  BROWSER_TIMEOUT: "60000"
  REDIS_URL: "redis://cloudnote-redis:6379/0"

