apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnote-redis
  namespace: cloudnote
  labels:
    app: cloudnote-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudnote-redis
  template:
    metadata:
      labels:
        app: cloudnote-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudnote-redis
  namespace: cloudnote
spec:
  selector:
    app: cloudnote-redis
  ports:
  - port: 6379
    targetPort: 6379
